name: npm
on:
  push:
    branches: [master]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
      - run: npm i -g yarn@1
      - run: yarn config set network-timeout 300000
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: npx pleb@6 publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
