name: tests
on: [push, pull_request]
jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn@1
      - run: yarn config set network-timeout 300000
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn add react@17 react-dom@17 --dev -W
      - run: yarn test:browser
